### ISSUE TITLE
D4 Look and feel 

### ISSUE THREAD

**Issue by jadynlaila** [jadynlaila/Study_Group_Platform#79]

**Comment by vsv7nau** [comment]
<img width="1728" alt="LOG IN" src="https://github.com/user-attachments/assets/b980884b-cebb-43ab-b080-9eb7e86456fb">
<img width="1728" alt="LANDING PAGE SIZE ADJUSTMENT" src="https://github.com/user-attachments/assets/f0d62910-b455-4939-9f7d-93067052e535">
![WIRE FRAME](https://github.com/user-attachments/assets/9f079168-0e9a-42f9-992c-d4b9b0dbd73f)

NOTE: These screenshots are pulled from our Figma Project and are not representative of the current state of our product

When we first started this project, we quickly realized that if we wanted to design a groupchat-focused-webapp that appeals to college students we'll have to compete directly with methods that already exist, for example: Snapchat, Groupme, Discord. With those existing products in mind, our approach was simplicity and minimalism whilst trimming out the fat that the other products mentioned offer ( features not necessary for an academically focused product such as Snapchats Location services, GroupMe's Built in Meme-Maker, Discords Game Linking Functionality ) and instead implement curated features meant to exclusively suit a students success in college not only academically but socially . As you can see in our screenshots our UI is very simple and doesn't overwhelm the user with too many options at once, this was intentional and reflective of what we heard in many of our interviews.

// UNFINISHED, WILL EDIT LATER //
